spring:
  application:
    name: user-center
  datasource:
    username: root
    password: wszqy123.
    url: jdbc:mysql://43.143.226.184:3306/usercenter?useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置session的存储方式
  session:
    timeout: 86400
    store-type: redis
  redis:
    password: wszqy123.
    port: 6379
    host: 43.143.226.184
    database: 1
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    #    mybatis-plus 关闭驼峰转换下划线功能
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 增加统一前缀/api
server:
  servlet:
    context-path: /api
    session:
      cookie:
        domain: https://springboot-8xuy-37303-4-1317328802.sh.run.tcloudbase.com
        same-site: lax
        secure: false

aliyun:
  oss:
    file:
      endpoint:  oss-cn-chengdu.aliyuncs.com
      keyid: LTAI5tLeKHHUj8d7vNZcSvbf
      keysecret: vm9vQkynjwudvRbwR1IpzeRCQAyyyt
      bucketname: wuxie-image
